overflow_delimited_expr = true
newline_style = "Unix"
merge_imports = true
reorder_impl_items = true
fn_single_line = false
blank_lines_upper_bound = 2
ignore = [
    "examples/",
    "tests/"
]
comment_width = 120
max_width = 120
inline_attribute_width = 120
